"""CRM ingestion: Auto Loader -> streaming bronze tables (one per CRM entity).

Inputs
------
Raw CSV files dropped by the CRM generator under::

    <landing>/crm/<entity>/dt=YYYY-MM-DD/*.csv

for each entity in ``CRM_ENTITIES`` (accounts, contacts, leads, opportunities,
opportunity_line_items, quotes, contracts, activities, cases, users,
territories).

Outputs
-------
One streaming Delta bronze table per entity, named ``bronze_crm_<entity>``
(published into the pipeline's UC target catalog + ``bronze`` schema). Each
table is an append-only, incrementally-loaded landing of the raw source with
the standard bronze audit columns added. **No business transformation** happens
here — bronze is a faithful, typed-as-string-friendly copy of source.

How it works (DLT + Auto Loader concepts)
-----------------------------------------
* ``@dlt.table`` declares a materialised table in the pipeline graph.
* Reading via ``spark.readStream.format("cloudFiles")`` (= Auto Loader) makes
  the table a **streaming table**: each pipeline run processes only *new* files
  (tracked via the schema/checkpoint location), so re-runs are incremental and
  idempotent.
* ``cloudFiles.schemaLocation`` is where Auto Loader stores the inferred schema
  and tracks **schema evolution** (new columns appearing in later files).
* ``cloudFiles.schemaEvolutionMode = addNewColumns`` lets the table absorb new
  source columns automatically; ``rescuedDataColumn`` captures any data that
  did not fit the current schema into ``_rescued_data`` instead of dropping it.

DQ
--
Ingestion is deliberately permissive (we never want to *lose* raw data at the
front door). We attach only a soft warn-level expectation that the source file
path is known; real validation happens in silver. Malformed/extra fields are
preserved in ``_rescued_data`` for later quarantine (see bronze/README.md).

The table definitions are generated by a small factory loop over
``CRM_ENTITIES`` to stay DRY — every entity gets an identical ingestion shape.
"""

from __future__ import annotations

import dlt

from pyspark.sql import functions as F

# DLT loads all pipeline files together, so this sibling import resolves.
from src.pipelines._common import (
    CRM_ENTITIES,
    landing_glob,
    schema_location,
    with_audit_columns,
)

SOURCE_SYSTEM = "crm"


def _make_bronze_table(entity: str) -> None:
    """Register one streaming bronze table for a CRM ``entity``.

    Defined inside a factory so the loop below can stamp out identical tables.
    The decorated inner function is what DLT discovers and materialises.
    """

    @dlt.table(
        name=f"bronze_crm_{entity}",
        comment=f"Raw CRM {entity} landed via Auto Loader (append-only bronze).",
        table_properties={
            "quality": "bronze",
            "pipelines.reset.allowed": "false",  # protect raw history from full refresh
            "delta.enableChangeDataFeed": "true",  # let silver read CDF if desired
        },
    )
    # Soft, warn-only expectation: we record violations but never drop/fail at
    # ingestion. ``_source_file`` should always be populated by _metadata.
    @dlt.expect("valid_source_file", "_source_file IS NOT NULL")
    def _bronze_table():
        df = (
            spark.readStream.format("cloudFiles")  # noqa: F821 (spark runtime global)
            .option("cloudFiles.format", "csv")
            .option("cloudFiles.schemaLocation", schema_location(SOURCE_SYSTEM, entity))
            .option("cloudFiles.schemaEvolutionMode", "addNewColumns")
            .option("cloudFiles.inferColumnTypes", "true")
            .option("header", "true")
            .option("rescuedDataColumn", "_rescued_data")
            # mode for the rescued column: keep going, don't fail on bad rows.
            .option("cloudFiles.allowOverwrites", "false")
            .load(landing_glob(SOURCE_SYSTEM, entity))
        )
        # Add bronze audit columns (_ingested_at/_source_file/_batch_id and a
        # uniform _rescued_data). _batch_id defaults to ingest date.
        return with_audit_columns(df).withColumn(
            "_source_system", F.lit(SOURCE_SYSTEM)
        )

    # Return nothing; the decorator already registered the table with DLT.


# Factory loop — stamp out one streaming bronze table per CRM entity.
for _entity in CRM_ENTITIES:
    _make_bronze_table(_entity)
