"""CRM ingestion: Auto Loader -> streaming bronze tables (one per CRM entity).

Inputs
------
Raw CSV files dropped by the CRM generator under::

    <landing>/crm/<entity>/dt=YYYY-MM-DD/*.csv

for each entity in ``CRM_ENTITIES`` (accounts, contacts, leads, opportunities,
opportunity_line_items, quotes, contracts, activities, cases, users,
territories).

Outputs
-------
One streaming Delta bronze table per entity, named ``bronze_crm_<entity>``
(published into the pipeline's UC target catalog + ``bronze`` schema). Each
table is an append-only, incrementally-loaded landing of the raw source with
the standard bronze audit columns added. **No business transformation** happens
here — bronze is a faithful, typed-as-string-friendly copy of source.

How it works (DLT + Auto Loader concepts)
-----------------------------------------
* ``@dlt.table`` declares a materialised table in the pipeline graph.
* Reading via ``spark.readStream.format("cloudFiles")`` (= Auto Loader) makes
  the table a **streaming table**: each pipeline run processes only *new* files
  (tracked via the schema/checkpoint location), so re-runs are incremental and
  idempotent.
* ``cloudFiles.schemaLocation`` is where Auto Loader stores the inferred schema
  and tracks **schema evolution** (new columns appearing in later files).
* ``cloudFiles.schemaEvolutionMode = addNewColumns`` lets the table absorb new
  source columns automatically; ``rescuedDataColumn`` captures any data that
  did not fit the current schema into ``_rescued_data`` instead of dropping it.

DQ
--
Ingestion is deliberately permissive (we never want to *lose* raw data at the
front door). We attach only a soft warn-level expectation that the source file
path is known; real validation happens in silver. Malformed/extra fields are
preserved in ``_rescued_data`` for later quarantine (see bronze/README.md).

The table definitions are generated by a small factory loop over
``CRM_ENTITIES`` to stay DRY — every entity gets an identical ingestion shape.
"""

from __future__ import annotations

import dlt

from pyspark.sql import functions as F

# ---------------------------------------------------------------------------
# Inlined from src/pipelines/_common.py — serverless DLT cannot reliably IMPORT
# a .py from /Workspace files (OSError Errno 5), so the shared helpers are
# inlined here. _common.py remains the source of truth for local/test use.
# ---------------------------------------------------------------------------
from pyspark.sql import DataFrame  # noqa: F401 (inlined helper annotations)
from pyspark.sql.column import Column  # noqa: F401

# ---------------------------------------------------------------------------
# Entity registries — single source of truth, reused by the Auto Loader
# factories so the ingestion files stay DRY.
# ---------------------------------------------------------------------------

CRM_ENTITIES: list[str] = [
    "accounts", "contacts", "leads", "opportunities", "opportunity_line_items",
    "quotes", "contracts", "activities", "cases", "users", "territories",
]

ERP_ENTITIES: list[str] = [
    "customers", "vendors", "products", "sales_orders", "sales_order_items",
    "billing_documents", "invoices", "payments", "purchase_orders",
    "gl_entries", "cost_centers", "profit_centers", "currency_rates",
]

REFERENCE_ENTITIES: list[str] = [
    "fiscal_calendar", "product_hierarchy", "currency_rates", "country_codes",
]


# ---------------------------------------------------------------------------
# Configuration getters
# ---------------------------------------------------------------------------

def get_catalog(default: str = "cdp_dev") -> str:
    """Return the target Unity Catalog name.

    Reads ``cdp.catalog`` from the Spark config (set by the DLT pipeline
    ``configuration`` block / bundle ``var.catalog``). Falls back to
    ``cdp_dev`` so the module is safe to import even if the key is unset.
    """
    return spark.conf.get("cdp.catalog", default)  # noqa: F821 (spark is a runtime global)


def get_landing_path(default: str = "/Volumes/cdp_dev/landing/files") -> str:
    """Return the root landing path/Volume for raw source files.

    Reads ``cdp.landing_path`` from the Spark config. The generators write to::

        <landing>/crm/<entity>/dt=YYYY-MM-DD/*.csv
        <landing>/erp/<entity>/dt=YYYY-MM-DD/*.csv
        <landing>/reference/<entity>/*.csv

    Trailing slashes are stripped so callers can safely f-string a suffix.
    """
    return spark.conf.get("cdp.landing_path", default).rstrip("/")  # noqa: F821


def landing_glob(source_system: str, entity: str) -> str:
    """Build the Auto Loader input path for one source entity.

    ``source_system`` is one of ``crm`` / ``erp`` / ``reference``. We point
    Auto Loader at the *entity* directory and let it walk the ``dt=...``
    partitions (``cloudFiles`` discovers new files under the path over time).
    """
    return f"{get_landing_path()}/{source_system}/{entity}"


def schema_location(source_system: str, entity: str) -> str:
    """Per-entity schema/checkpoint location for Auto Loader schema inference.

    Auto Loader persists the inferred schema (and tracks evolution) here. It
    lives under the landing root in a hidden ``_schemas`` folder, namespaced by
    source + entity so entities never collide.
    """
    return f"{get_landing_path()}/_schemas/{source_system}/{entity}"


# ---------------------------------------------------------------------------
# Audit columns
# ---------------------------------------------------------------------------

def with_audit_columns(df: DataFrame, batch_id: str | None = None) -> DataFrame:
    """Append the standard bronze audit columns to a DataFrame.

    Convention (see src/pipelines/bronze/README.md):
      * ``_ingested_at`` -- processing-time the row was ingested
      * ``_source_file`` -- the file the row came from (``_metadata.file_path``)
      * ``_batch_id``    -- logical batch label (defaults to ingest date)
      * ``_rescued_data`` -- Auto Loader's rescued-data column (already present
        on the streaming DataFrame when ``rescuedDataColumn`` is configured;
        we leave it as-is and only add it as NULL if missing so the bronze
        schema is uniform across entities).

    ``_metadata`` is a hidden struct column Auto Loader/Spark exposes on file
    sources; ``_metadata.file_path`` is the modern replacement for the
    deprecated ``input_file_name()``.
    """
    out = (
        df.withColumn("_ingested_at", F.current_timestamp())
          .withColumn("_source_file", F.col("_metadata.file_path"))
    )
    # batch id defaults to the ingest date (yyyy-MM-dd) when not supplied.
    if batch_id is None:
        out = out.withColumn("_batch_id", F.date_format(F.current_timestamp(), "yyyy-MM-dd"))
    else:
        out = out.withColumn("_batch_id", F.lit(batch_id))

    # Guarantee a uniform _rescued_data column even if a source had no rescues.
    if "_rescued_data" not in out.columns:
        out = out.withColumn("_rescued_data", F.lit(None).cast("string"))
    return out


# ---------------------------------------------------------------------------
# Normalisation helpers (used heavily by silver identity resolution)
# ---------------------------------------------------------------------------

# Common company-name "noise" suffixes we strip to improve deterministic match.
_LEGAL_SUFFIXES = [
    "incorporated", "inc", "corporation", "corp", "company", "co",
    "limited", "ltd", "llc", "llp", "lp", "plc", "gmbh", "ag", "sa", "nv",
    "bv", "pty", "group", "holdings", "the",
]


def normalize_name(col: "Column | str") -> Column:
    """Return a normalised company/person name column for fuzzy-deterministic match.

    Steps: lower-case -> strip accents-ish punctuation -> collapse whitespace ->
    drop common legal suffixes -> trim. This produces a stable join key so
    "Apex Industries, Inc." and "apex industries inc" resolve to the same key.

    Accepts either a column name (str) or an existing ``Column``.
    """
    c = F.col(col) if isinstance(col, str) else col
    c = F.lower(c)
    # Remove anything that is not a letter, digit or space.
    c = F.regexp_replace(c, r"[^a-z0-9\s]", " ")
    # Drop standalone legal-suffix tokens (word-boundary match).
    for suffix in _LEGAL_SUFFIXES:
        c = F.regexp_replace(c, rf"\b{suffix}\b", " ")
    # Collapse repeated whitespace and trim.
    c = F.trim(F.regexp_replace(c, r"\s+", " "))
    return c


def normalize_domain(col: "Column | str") -> Column:
    """Extract a normalised email/web domain (lower-cased, no leading www.).

    From an email like ``a.b@apex.com`` returns ``apex.com``; from a bare
    domain it just normalises case and strips ``www.``.
    """
    c = F.col(col) if isinstance(col, str) else col
    c = F.lower(F.trim(c))
    # If it's an email, take the part after '@'.
    c = F.when(c.contains("@"), F.split(c, "@").getItem(1)).otherwise(c)
    c = F.regexp_replace(c, r"^www\.", "")
    return c


def surrogate_key(*cols: "Column | str") -> Column:
    """Deterministic surrogate-key hash from one or more business-key columns.

    Uses SHA-2(256) over a ``||``-joined, null-safe concatenation so the same
    business key always maps to the same surrogate across runs (stable, unlike
    monotonically_increasing_id()).
    """
    resolved = [F.col(c) if isinstance(c, str) else c for c in cols]
    coalesced = [F.coalesce(c.cast("string"), F.lit("")) for c in resolved]
    return F.sha2(F.concat_ws("||", *coalesced), 256)


def crosswalk_path() -> str:
    """Path to the CRM<->ERP crosswalk JSON emitted by the data generators.

    The generators persist a shared identity map at
    ``<landing>/_crosswalk/crm_erp_crosswalk.json`` (see data_gen/common.py).
    Silver identity resolution reads it as a deterministic match assist.
    """
    return f"{get_landing_path()}/_crosswalk/crm_erp_crosswalk.json"

SOURCE_SYSTEM = "crm"


def _make_bronze_table(entity: str) -> None:
    """Register one streaming bronze table for a CRM ``entity``.

    Defined inside a factory so the loop below can stamp out identical tables.
    The decorated inner function is what DLT discovers and materialises.
    """

    @dlt.table(
        name=f"bronze_crm_{entity}",
        comment=f"Raw CRM {entity} landed via Auto Loader (append-only bronze).",
        table_properties={
            "quality": "bronze",
            "pipelines.reset.allowed": "false",  # protect raw history from full refresh
            "delta.enableChangeDataFeed": "true",  # let silver read CDF if desired
        },
    )
    # Soft, warn-only expectation: we record violations but never drop/fail at
    # ingestion. ``_source_file`` should always be populated by _metadata.
    @dlt.expect("valid_source_file", "_source_file IS NOT NULL")
    def _bronze_table():
        df = (
            spark.readStream.format("cloudFiles")  # noqa: F821 (spark runtime global)
            .option("cloudFiles.format", "csv")
            .option("cloudFiles.schemaLocation", schema_location(SOURCE_SYSTEM, entity))
            .option("cloudFiles.schemaEvolutionMode", "addNewColumns")
            .option("cloudFiles.inferColumnTypes", "true")
            .option("header", "true")
            .option("rescuedDataColumn", "_rescued_data")
            # mode for the rescued column: keep going, don't fail on bad rows.
            .option("cloudFiles.allowOverwrites", "false")
            .load(landing_glob(SOURCE_SYSTEM, entity))
        )
        # Add bronze audit columns (_ingested_at/_source_file/_batch_id and a
        # uniform _rescued_data). _batch_id defaults to ingest date.
        return with_audit_columns(df).withColumn(
            "_source_system", F.lit(SOURCE_SYSTEM)
        )

    # Return nothing; the decorator already registered the table with DLT.


# Factory loop — stamp out one streaming bronze table per CRM entity.
for _entity in CRM_ENTITIES:
    _make_bronze_table(_entity)
